---
title: "FinalProjectDST1"
author: "Antonio Dehesa"
date: "2023-07-07"
output: pdf_document
---

```{r setup, include=TRUE, warning=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Libraries
library(tidyverse) # To remove NAs from a single column in a dataframe
```

```{r}
# We load the dataset
data <- read.csv("salary_responses.csv")
# We explore basic information of the dataset
head(data)
```

```{r}
# Now we clean the data from values we do not need
x <- data[, -c(1,5, 10)]
# Then we can change the names of the columns
col_names <- c("Age", "Industry", "Job Title", "Annual Salary", "Bonus", "Currency", "Alternate Currency", "Country", "US State", "US City", "Work experience", "Work experience in field", "Education", "Gender", "Race")
colnames(x) <- col_names
# Now we remove NAs from critical columns
x[x$`Annual Salary` == "",] <- NA
x[x$Education == "",] <- NA
x <- x %>% drop_na(c("Annual Salary", "Education"))

# As we cannot drop observations where there was no bonus, we need to set NA values to 0 to be able to add them
x[is.na(x$Bonus), 5] <- 0 

# Now we transform the column "Annual Salary" and "Bonus" from character to integer
x$`Annual Salary` <- as.numeric(gsub(",", "", x$`Annual Salary`))
x$Bonus <- as.numeric(gsub(",", "", x$Bonus))
# Now we can combine columns "Annual Salary" and "Bonus" to get the column "Total"
x$Total <- x$`Annual Salary` + x$Bonus
x <- x[, -c(4,5)]
head(x)
```

